### ISSUE TITLE
Fastbreak false-positives

### ISSUE THREAD

**Issue by Trikolon** [gravitylow/AntiCheat#128]
Players experience problems with fastbreak when using any tool (e.g. picaxe). After a while it throws out false positives and their violation level is rising.

/anticheat debug: http://pastebin.com/d1d5nynj

(Default magic.yml configuration)

**Comment by gravitylow** [comment]
Possible dupe of https://github.com/h31ix/AntiCheat/issues/126

**Comment by Trikolon** [comment]
Might be, but it affects all types, so I created a seperate thread.

**Comment by jungfaha** [comment]
Our server also has the false positves and we know the members are not cheating.
What can we do to stop the false positives?
Please help. :)
We tried using the release build and the dev build, both have the same issue.
We use the fallowing plugins:
•Anti Cheat

•Anti X-Ray

•Essentials

•WhoIsInBed

•SchedualedAnnouncer

•WorldEdit

•BattleNight

Thank you for your time and understanding.

http://pastebin.com/cyHSb98H
a more detailed error report with different problems. http://pastebin.com/5E3Pgz4e

**Comment by gravitylow** [comment]
I believe to have fixed this in AntiCheat v1.4.3, try it out please.

**Comment by Trikolon** [comment]
Seems to be fixed. Thank you.

**Comment by Trikolon** [comment]
Still issues with fastbreaking and enchanted tools in 1.4.3

**Comment by gravitylow** [comment]
Only with enchanted tools or?

**Comment by Trikolon** [comment]
Mainly with them I think. Did not test this properly yet, many players had issues with it.

**Comment by Trikolon** [comment]
Development-Build #390 still throws out fastplacing errors when farming, the rest seems to be fine there.

**Comment by gravitylow** [comment]
Could you be more specific? Farming meaning what?

Also, could you describe the circumstance in which enchanted tools will cause these errors?

**Comment by Trikolon** [comment]
First of all fastbreaking false-positives (#390): Breaking all kind of crops with bare hands (Held mousebutton while going through field).
Debug-log: http://pastebin.com/2GwTEGvT

**Comment by Trikolon** [comment]
Tested all diamond tools with highest enchantment level on efficency, all fine. It is just the farming

**Comment by gravitylow** [comment]
I believe I've fixed this in the latest commit. Please let me know.

**Comment by Trikolon** [comment]
Not fixed for me in build #398  :/
New debug with more detailed messages: http://pastebin.com/3VDiB83Z

**Comment by Trikolon** [comment]
Noswing seems to be broken now. Triggers when destroying grass: http://pastebin.com/AanSHbE9

**Comment by gravitylow** [comment]
This should fix those:
https://github.com/h31ix/AntiCheat/commit/469aff5f935ce75c74862efd1d8c21ae862a7541

I hadn't properly been accounting carrots or potatoes. Just a small issue with those two things.

**Comment by Trikolon** [comment]
Thank you. Build #400 fixed all the issues concerning fastbreak  and noswing :)
