### ISSUE TITLE
false positive y-axis check when swimming

### ISSUE THREAD

**Issue by ZathrasNotTheOne** [gravitylow/AntiCheat#40]
> ver AntiCheat
> 11:15:29 [INFO] AntiCheat version 1.3-DEV-b156
> 11:15:29 [INFO] Prevention of hacks and other malicious tinkering on a Minecraft server.
> 11:15:29 [INFO] Author: H31IX
> 
> ver
> 11:21:46 [INFO] This server is running CraftBukkit version git-Bukkit-1.2.5-R3.0-b2203jnks (MC: 1.2.5) (Implementing API version 1.2.5-R3.0)

A player swimming across a lake gets y-axis messages and is teleported to the top of the water and then sinks again.  Eventually he gets kicked for y-axis hacking.

Another player has an indoor pool (roof overhead).  He gets in the water and all is fine.  As soon as he begins to swim with space bar, he gets teleported to the roof and a y-axis message is logged.  

11:17:09 [SEVERE] [AntiCheat] xxxx tried to fly on y-axis 

I believe this is related to the recent checkAscension() changes that detect upwards motion and use the getHighestBlockAt()

https://github.com/h31ix/AntiCheat/commit/b8dd6b0f585cf9df1d83d0cde0784f533cd2f27a

**Comment by SuperSpyTX** [comment]
It appears that H31IX's logical rewrite broke everything.

Possible reverting might be required.

**Comment by gravitylow** [comment]
Fixed here: http://ci.h31ix.net/job/AntiCheat/160/ , please reply and confirm that it is fixed.

**Comment by ghost** [comment]
When climbing a waterfall they will seem to still get this. They also get teleported around a bit somehow.

**Comment by gravitylow** [comment]
Are you using the latest dev build? I just tested this on it and it's working fine.

**Comment by ghost** [comment]
Just tested using build #167 and made a little waterfall and tried swimming up it. Get teleported around and the message:
[SEVERE] [AntiCheat] Player tried to fly on y-axis 

I also, if this helps, I noticed one time nearby on a vine I got teleported around a little bit somehow climbing up it.

**Comment by gravitylow** [comment]
Try this new one :) http://ci.h31ix.net/job/AntiCheat/168/

**Comment by gravitylow** [comment]
Assuming this is fixed after testing.
