### ISSUE TITLE
Visuals Check - False Positives List

### ISSUE THREAD

**Issue by SuperSpyTX** [gravitylow/AntiCheat#80]
I'm in need of some help, because I've been away and I've heard some issues happening with the visuals check.  So i'm going to try and organize these multiple issues into one.  Because however I'm still at my dads, I won't be doing repairs until I get back.  You will know when I'm back and working on this if i assign myself to this ticket.

This may be the **worst** way to get an idea for false positives but it's easier if i can get it all in one issue so I can fix it one by one and ease the workload by the time I get back from dads.

What I want you all to do, is **re-test again using this build**: http://ci.h31ix.net/job/AntiCheat/202/

Then, I want you or someone else who is not opped/normal player and try to find the false positives.

If you catch a false positive, repeat it **5 times and be sure that's the one you want to report.**

Afterwards, then fill out this form and **submit it to this issue only.**  

```
Title (The bug with visuals check in less than 5 words) (OPTIONAL):

Description (Explain it as much ass possible, no "I opened a chest and it got detected"):
```

**There is to be no other issues created and ONLY this issue specifically.  I will close all other issues regarding visuals check until this one is closed.**

Also this issue's marked as "Enhancement" because I'll not only fix bugs, but also possibly enhance the check as well.  Enhance as in, not creating new bugs at the same time.

Here's what **I'm aware of and something you don't file on here, unless I forgot to add to this list:**
- Placing blocks in the water (Fixed).
- Interacting on top of stone pressure plate (Fixed).
- Right clicking a chest with a trap door on top.
- Commented out interactable blocks in Utilities.java are not working with visuals check.

**Comment by Rojoss** [comment]
Right clicking chests don't actually open the chest.
Doesn't matter if there is a trapdoor on top or not.
Repeating this will get the player kicked
Some times it's working fine though but most of the times not and then players aren't be able to open the chests.
And most of the times this only happens when opening it from the top.

**Comment by gravitylow** [comment]
@worstboy32 Fixed in latest dev

**Comment by Rojoss** [comment]
Thanks h32ix :)

**Comment by Rojoss** [comment]
Edit:
Not fixed.
Still getting kicked for trying to open chests.
2012-06-18 20:08:54 [INFO] [AntiCheat] worstboy32 tried to interact with an object that they couldn't see
2012-06-18 20:08:54 [INFO] [AntiCheat] worstboy32 tried to interact with an object that they couldn't see
2012-06-18 20:08:54 [INFO] [AntiCheat] worstboy32 tried to interact with an object that they couldn't see
2012-06-18 20:08:54 [INFO] [AntiCheat] worstboy32 tried to interact with an object that they couldn't see
2012-06-18 20:08:55 [INFO] [AntiCheat] worstboy32 tried to interact with an object that they couldn't see
2012-06-18 20:08:55 [INFO] [AntiCheat] worstboy32 tried to interact with an object that they couldn't see
2012-06-18 20:08:55 [INFO] [AntiCheat] worstboy32 tried to interact with an object that they couldn't see
2012-06-18 20:08:55 [INFO] [AntiCheat] worstboy32 tried to interact with an object that they couldn't see

**Comment by gravitylow** [comment]
Just... opening them? Without anything on top? Pics please?

**Comment by Rojoss** [comment]
Think you can ignore my comment.
Asked players if they still had issues and they said not.
might just lagged or something dono if it happens again i will comment back with screenshot/video

**Comment by gravitylow** [comment]
Um, excuse me? You're commenting on an issue we put together to round all these errors up... while replying my comment which was addressing YOUR issue.... and telling me I'm ignoring you...?

**Comment by Rojoss** [comment]
I meant to say that my comment wasn't valid.
It was on my PvP server and that one didn't had the last dev build yet.
So if i would say that i get errors i would be lying.
That's why i said ignore my comment.
Nobody on my servers complained so far that they got kicked for opening chests.
So i'm pretty sure it's fixed.

**Comment by gravitylow** [comment]
Lol, totally misread that don't know it why that was not obvious... sorry about that! Good to hear.

**Comment by Rojoss** [comment]
damm it's happening still.
Got multiple reports today again and this time im sure it's the last version.
And yes it's just opening with nothing on top.
Or maybe a sign or torch or something but also without.
Here some reports:
http://fantasywar.net/forum/post/last/m/3260426/viewthread/3388819-anticheat-bug-got-me-jailed-twice-ohh-wait-now-im-again#last
http://fantasywar.net/forum/post/last/m/3260426/viewthread/3388012-getting-jailed#last

So hope you can look at it once again.

**Comment by kjhf** [comment]
Confirmed on our server. Tests show that SOUTHERN- and WESTERN- facing buttons trigger the bug (the play faces North / East), but Northern- and Eastern-facing buttons (player faces south or west) work correctly.

**Comment by kjhf** [comment]
To all: For now, I added anticheat.check.visual
permission to the base group (so all groups have that).
It bypasses the visual check so no more false positives (but remember to remove when fixed obviously).

For convenience, the command is here:
/pex group guest add anticheat.check.visual
